name: Build Tauri App
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest, macos-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: install app dependencies
        run: npm install
        working-directory: app

      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          projectPath: app
          tagName: v__VERSION__
          releaseName: 'UniQlock v__VERSION__'
          releaseBody: 'Download the installers below to run the app on your PC/Mac.'
          releaseDraft: true
          prerelease: false
